# Generated by Django 3.0.5 on 2020-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200501_1656'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookinstance',
            constraint=models.UniqueConstraint(fields=('type', 'registration'), name='unique_booking'),
        ),
    ]
