# Generated by Django 3.0.5 on 2020-05-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20200501_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
